version: '3.7'
services:
  switch_python_lib:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - /workspace/src/venv
      - /workspace/docs/node_modules
    networks:
      - switch-network
networks:
  switch-network:
    external:
      name:
        dev-network
